### PR TITLE
Perform document content review

### PR DESCRIPTION
**Pull request by gaskinae**
I reviewed spelling, grammar, semantics, and general consistency throughout the document.

### CODE REVIEW

**Comment by gaskinae** [comment]
I also want to check the use of the word "workflows" throughout the document. It starts off being referred to as a synonym for "bioinformatics pipeline" (which I don't disagree with), but later in the document there is some possibility for confusion where "workflow" is used more ambiguously to refer to "research workflows". For example:

"This documentation promotes transparency, facilitates replication, and enables researchers to more effectively integrate the pipeline into their workflows.."

**Review by kevinlibuit — APPROVED** [review]
Thanks for the thorough review! Great catches.

**Comment by kevinlibuit** [comment]
> I also want to check the use of the word "workflows" throughout the document. It starts off being referred to as a synonym for "bioinformatics pipeline" (which I don't disagree with), but later in the document there is some possibility for confusion where "workflow" is used more ambiguously to refer to "research workflows". For example:
> 
> "This documentation promotes transparency, facilitates replication, and enables researchers to more effectively integrate the pipeline into their workflows.."

Oof, this is a good point. Always difficult when such general words get technical definitions. Would it be more clear to describe these _workflows_ as "processes"?

**Comment by gaskinae** [comment]
Yeah I agree with that suggestion! Research processes, platforms, services, something in that arena. I reckon "processes" suffices in this context :)

**Pull request merged**
